apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trabajo
  namespace: alumno-ALUMNO
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: entorno
  namespace: alumno-ALUMNO
spec:
  replicas: 1                         # 0 = entorno apagado; 1 = encendido
  selector:
    matchLabels: { app: entorno }
  template:
    metadata:
      labels: { app: entorno }
    spec:
      containers:
        - name: practicas
          image: laboratorio-registry:6001/fso:latest
          ports:
            - containerPort: 22
          volumeMounts:
            - name: trabajo
              mountPath: /home/alumno
      volumes:
        - name: trabajo
          persistentVolumeClaim:
            claimName: trabajo
---
apiVersion: v1
kind: Service
metadata:
  name: ssh
  namespace: alumno-ALUMNO
spec:
  type: NodePort
  selector: { app: entorno }
  ports:
    - port: 22
      targetPort: 22
      nodePort: 30022       # un puerto distinto por alumno (30022, 30023, ...)
                            # dentro del rango mapeado en el paso 4